services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: precision_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  
  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - ./precision-auto:/app
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - INTERNAL_API_BASE_URL=http://api:8000
    depends_on:
      - api

  # GUI for pgadmin4 (this is just for local development in the future we will add some func. for production db)
  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: {}
