version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    environment:
      - LANG=en_US.utf8  
      - LC_ALL=en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Wait for healthy DB
    command: >
      sh -c "python init_db.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000  
    depends_on:
      - backend

volumes:
  postgres_data: